import { Sector, JobDefinition, EquipmentDefinition, LocationDefinition, IncidentReasonDefinition } from '../types';

export const mockSectors: Sector[] = [
  { id: 'sec-1',  name: 'İnşaat',              code: 'CONST', description: 'Bina, köprü ve altyapı inşaatı',           createdAt: new Date().toISOString() },
  { id: 'sec-2',  name: 'Lojistik & Taşımacılık', code: 'LOGIS', description: 'Kara, hava ve deniz taşımacılığı ile depolama', createdAt: new Date().toISOString() },
  { id: 'sec-3',  name: 'Sanayi / Üretim',     code: 'INDUS', description: 'Metal, plastik, tekstil ve diğer imalat',  createdAt: new Date().toISOString() },
  { id: 'sec-4',  name: 'Enerji',               code: 'ENRGY', description: 'Elektrik, doğalgaz, petrol ve yenilenebilir enerji', createdAt: new Date().toISOString() },
  { id: 'sec-5',  name: 'Tarım & Hayvancılık',  code: 'AGRI',  description: 'Tarla, sera, bahçe ve hayvancılık faaliyetleri', createdAt: new Date().toISOString() },
  { id: 'sec-6',  name: 'Sağlık & Sosyal Hizmetler', code: 'HLTH', description: 'Hastane, klinik ve bakım hizmetleri',  createdAt: new Date().toISOString() },
  { id: 'sec-7',  name: 'Gıda & İçecek',        code: 'FOOD',  description: 'Gıda üretimi, işleme ve ambalajlama',     createdAt: new Date().toISOString() },
  { id: 'sec-8',  name: 'Madencilik',            code: 'MINE',  description: 'Kömür, metal madeni ve taş ocağı',       createdAt: new Date().toISOString() },
  { id: 'sec-9',  name: 'Kimya & Petrokimya',    code: 'CHEM',  description: 'Kimyasal üretim ve ilaç sanayi',         createdAt: new Date().toISOString() },
  { id: 'sec-10', name: 'Orman & Kağıt',         code: 'WOOD',  description: 'Ormancılık, ahşap işleme ve kağıt üretimi', createdAt: new Date().toISOString() },
  { id: 'sec-11', name: 'Denizcilik',            code: 'MARI',  description: 'Gemi inşa, liman ve deniz taşımacılığı', createdAt: new Date().toISOString() },
  { id: 'sec-12', name: 'Havacılık',             code: 'AVIA',  description: 'Havalimanı, uçak bakım ve operasyonları', createdAt: new Date().toISOString() },
  { id: 'sec-13', name: 'Otomotiv',              code: 'AUTO',  description: 'Araç üretimi, bakım ve servis',          createdAt: new Date().toISOString() },
  { id: 'sec-14', name: 'Tekstil & Konfeksiyon', code: 'TEXT',  description: 'Tekstil üretimi ve dikiş atölyeleri',    createdAt: new Date().toISOString() },
  { id: 'sec-15', name: 'Perakende & Hizmet',    code: 'RETL',  description: 'Mağaza, restoran ve kamu hizmetleri',    createdAt: new Date().toISOString() },
];

export const mockJobDefinitions: JobDefinition[] = [
  // ─── İNŞAAT ───
  { id: 'job-1',  sectorId: 'sec-1', name: 'Şantiye Şefi',           riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-2',  sectorId: 'sec-1', name: 'İnşaat Mühendisi',       riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-3',  sectorId: 'sec-1', name: 'İnşaat İşçisi',          riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-4',  sectorId: 'sec-1', name: 'Kalıpçı',                riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-5',  sectorId: 'sec-1', name: 'Demirci / Demir Bükücü', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-6',  sectorId: 'sec-1', name: 'Elektrikçi',             riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-7',  sectorId: 'sec-1', name: 'Betoncu',                riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-8',  sectorId: 'sec-1', name: 'Marangoz',               riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-9',  sectorId: 'sec-1', name: 'Vinç Operatörü',         riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-10', sectorId: 'sec-1', name: 'İskele Ustası',          riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-11', sectorId: 'sec-1', name: 'Sıvacı / Badanacı',      riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-12', sectorId: 'sec-1', name: 'Su / Doğalgaz Tesisatçısı', riskLevel: 'Orta', createdAt: new Date().toISOString() },
  { id: 'job-13', sectorId: 'sec-1', name: 'Çatı Ustası',            riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-14', sectorId: 'sec-1', name: 'Yol / Altyapı İşçisi',  riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  // ─── LOJİSTİK ───
  { id: 'job-15', sectorId: 'sec-2', name: 'Forklift Operatörü',     riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-16', sectorId: 'sec-2', name: 'Depo Görevlisi',         riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-17', sectorId: 'sec-2', name: 'TIR / Tır Şoförü',      riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-18', sectorId: 'sec-2', name: 'Kamyon Şoförü',          riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-19', sectorId: 'sec-2', name: 'Sevkiyat Sorumlusu',     riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'job-20', sectorId: 'sec-2', name: 'Yükleme Personeli',      riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-21', sectorId: 'sec-2', name: 'Depo Müdürü',            riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'job-22', sectorId: 'sec-2', name: 'Lojistik Uzmanı',        riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  // ─── SANAYİ / ÜRETİM ───
  { id: 'job-23', sectorId: 'sec-3', name: 'Üretim Operatörü',       riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-24', sectorId: 'sec-3', name: 'Makine Bakım Teknisyeni', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-25', sectorId: 'sec-3', name: 'Kalite Kontrol Uzmanı',  riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'job-26', sectorId: 'sec-3', name: 'Kaynakçı',               riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-27', sectorId: 'sec-3', name: 'Tornacı',                riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-28', sectorId: 'sec-3', name: 'Freze Operatörü',        riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-29', sectorId: 'sec-3', name: 'CNC Operatörü',          riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-30', sectorId: 'sec-3', name: 'Üretim Mühendisi',       riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  // ─── ENERJİ ───
  { id: 'job-31', sectorId: 'sec-4', name: 'Elektrik Teknisyeni',    riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-32', sectorId: 'sec-4', name: 'Yüksek Gerilim Operatörü', riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-33', sectorId: 'sec-4', name: 'Petrol / Gaz İşçisi',   riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-34', sectorId: 'sec-4', name: 'Nükleer Tesis Operatörü', riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-35', sectorId: 'sec-4', name: 'Rüzgar Türbini Teknisyeni', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-36', sectorId: 'sec-4', name: 'Güneş Paneli Kurulumcusu', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  // ─── TARIM ───
  { id: 'job-37', sectorId: 'sec-5', name: 'Traktör Operatörü',      riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-38', sectorId: 'sec-5', name: 'Tarım İşçisi',           riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-39', sectorId: 'sec-5', name: 'Sera Görevlisi',         riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'job-40', sectorId: 'sec-5', name: 'Ziraat Mühendisi',       riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'job-41', sectorId: 'sec-5', name: 'Hasat İşçisi',           riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-42', sectorId: 'sec-5', name: 'Hayvan Bakıcısı',        riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  // ─── SAĞLIK ───
  { id: 'job-43', sectorId: 'sec-6', name: 'Hemşire',                riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-44', sectorId: 'sec-6', name: 'Hasta Bakıcı',           riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-45', sectorId: 'sec-6', name: 'Temizlik Görevlisi',     riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-46', sectorId: 'sec-6', name: 'Laborant',               riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-47', sectorId: 'sec-6', name: 'Acil Servis Görevlisi',  riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-48', sectorId: 'sec-6', name: 'Ambulans Sürücüsü',      riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  // ─── GIDA ───
  { id: 'job-49', sectorId: 'sec-7', name: 'Gıda Teknikeri',         riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'job-50', sectorId: 'sec-7', name: 'Paketleme Operatörü',    riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-51', sectorId: 'sec-7', name: 'Soğuk Hava Deposu Görevlisi', riskLevel: 'Orta', createdAt: new Date().toISOString() },
  { id: 'job-52', sectorId: 'sec-7', name: 'Kasap / Kesimhane İşçisi', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-53', sectorId: 'sec-7', name: 'Fırın Operatörü',        riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  // ─── MADENCİLİK ───
  { id: 'job-54', sectorId: 'sec-8', name: 'Madenci',                riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-55', sectorId: 'sec-8', name: 'Patlatma Uzmanı',        riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-56', sectorId: 'sec-8', name: 'Kazı Makinesi Operatörü', riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-57', sectorId: 'sec-8', name: 'Maden Mühendisi',        riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-58', sectorId: 'sec-8', name: 'Taş Ocağı İşçisi',       riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  // ─── KİMYA ───
  { id: 'job-59', sectorId: 'sec-9', name: 'Kimyager',               riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-60', sectorId: 'sec-9', name: 'Reaktör Operatörü',      riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-61', sectorId: 'sec-9', name: 'İlaç Üretim Teknisyeni', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-62', sectorId: 'sec-9', name: 'Boru Tesisatçısı',       riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  // ─── ORMAN & KAĞIT ───
  { id: 'job-63', sectorId: 'sec-10', name: 'Orman İşçisi',          riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-64', sectorId: 'sec-10', name: 'Testere Operatörü',     riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-65', sectorId: 'sec-10', name: 'Kereste İşçisi',        riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-66', sectorId: 'sec-10', name: 'Kağıt Makinesi Operatörü', riskLevel: 'Orta', createdAt: new Date().toISOString() },
  // ─── DENİZCİLİK ───
  { id: 'job-67', sectorId: 'sec-11', name: 'Gemi Kaptanı',          riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-68', sectorId: 'sec-11', name: 'Gemi Makinisti',        riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-69', sectorId: 'sec-11', name: 'Liman İşçisi',          riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-70', sectorId: 'sec-11', name: 'Gemi İnşa İşçisi',      riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  // ─── HAVACLIK ───
  { id: 'job-71', sectorId: 'sec-12', name: 'Uçak Bakım Teknisyeni', riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'job-72', sectorId: 'sec-12', name: 'Yer Hizmetleri Görevlisi', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-73', sectorId: 'sec-12', name: 'Kargo Görevlisi',       riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  // ─── OTOMOTİV ───
  { id: 'job-74', sectorId: 'sec-13', name: 'Otomotiv Teknisyeni',   riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-75', sectorId: 'sec-13', name: 'Araç Boyacısı',         riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-76', sectorId: 'sec-13', name: 'Montaj Hattı İşçisi',   riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'job-77', sectorId: 'sec-13', name: 'Test Sürücüsü',         riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  // ─── TEKSTİL ───
  { id: 'job-78', sectorId: 'sec-14', name: 'Dokuma Operatörü',      riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-79', sectorId: 'sec-14', name: 'Dikiş Makinesi Operatörü', riskLevel: 'Orta', createdAt: new Date().toISOString() },
  { id: 'job-80', sectorId: 'sec-14', name: 'Boya / Apre İşçisi',   riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  // ─── PERAKENDİ ───
  { id: 'job-81', sectorId: 'sec-15', name: 'Kasiyer',               riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'job-82', sectorId: 'sec-15', name: 'Raf Görevlisi',         riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'job-83', sectorId: 'sec-15', name: 'Güvenlik Görevlisi',    riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'job-84', sectorId: 'sec-15', name: 'Temizlik Personeli',    riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
];

export const mockEquipmentDefinitions: EquipmentDefinition[] = [
  // ─── İNŞAAT ───
  { id: 'eq-1',  sectorId: 'sec-1', name: 'İskele',              category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-2',  sectorId: 'sec-1', name: 'Vinç',                category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-3',  sectorId: 'sec-1', name: 'Beton Mikseri',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-4',  sectorId: 'sec-1', name: 'Ekskavatör',          category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-5',  sectorId: 'sec-1', name: 'Buldozer',            category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-6',  sectorId: 'sec-1', name: 'Kompaktör',           category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-7',  sectorId: 'sec-1', name: 'Matkap / Kırıcı',    category: 'Tool',      createdAt: new Date().toISOString() },
  { id: 'eq-8',  sectorId: 'sec-1', name: 'Taşlama Makinesi',   category: 'Tool',      createdAt: new Date().toISOString() },
  { id: 'eq-9',  sectorId: 'sec-1', name: 'Kask',                category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-10', sectorId: 'sec-1', name: 'Emniyet Kemeri',      category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-11', sectorId: 'sec-1', name: 'Güvenlik Ayakkabısı', category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-12', sectorId: 'sec-1', name: 'Güvenlik Eldiveni',   category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-13', sectorId: 'sec-1', name: 'Gözlük / Yüz Siperliği', category: 'PPE',   createdAt: new Date().toISOString() },
  { id: 'eq-14', sectorId: 'sec-1', name: 'Reflektif Yelek',     category: 'PPE',       createdAt: new Date().toISOString() },
  // ─── LOJİSTİK ───
  { id: 'eq-15', sectorId: 'sec-2', name: 'Forklift',            category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-16', sectorId: 'sec-2', name: 'Reach Truck',         category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-17', sectorId: 'sec-2', name: 'Elektrikli Transpalet', category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-18', sectorId: 'sec-2', name: 'Manuel Transpalet',   category: 'Tool',      createdAt: new Date().toISOString() },
  { id: 'eq-19', sectorId: 'sec-2', name: 'Barkod Tarayıcı',     category: 'Tool',      createdAt: new Date().toISOString() },
  { id: 'eq-20', sectorId: 'sec-2', name: 'Yükleme Rampası',     category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-21', sectorId: 'sec-2', name: 'Palet Sargılama Makinesi', category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-22', sectorId: 'sec-2', name: 'Kanca / Zincir Takımı', category: 'Tool',   createdAt: new Date().toISOString() },
  // ─── SANAYİ ───
  { id: 'eq-23', sectorId: 'sec-3', name: 'Pres Makinesi',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-24', sectorId: 'sec-3', name: 'Torna Tezgahı',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-25', sectorId: 'sec-3', name: 'Freze Tezgahı',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-26', sectorId: 'sec-3', name: 'Taşlama Tezgahı',     category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-27', sectorId: 'sec-3', name: 'Kaynak Makinesi (MIG/TIG)', category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-28', sectorId: 'sec-3', name: 'CNC Tezgah',          category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-29', sectorId: 'sec-3', name: 'Kıyıcı / Giyotin',   category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-30', sectorId: 'sec-3', name: 'Bant Konveyör',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-31', sectorId: 'sec-3', name: 'Kaynak Maskesi',      category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-32', sectorId: 'sec-3', name: 'İş Önlüğü',          category: 'PPE',       createdAt: new Date().toISOString() },
  // ─── ENERJİ ───
  { id: 'eq-33', sectorId: 'sec-4', name: 'Jeneratör',           category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-34', sectorId: 'sec-4', name: 'Transformatör',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-35', sectorId: 'sec-4', name: 'Yüksek Gerilim Kablosu', category: 'Tool',  createdAt: new Date().toISOString() },
  { id: 'eq-36', sectorId: 'sec-4', name: 'İzole Alet Takımı',   category: 'Tool',      createdAt: new Date().toISOString() },
  { id: 'eq-37', sectorId: 'sec-4', name: 'Jeotermal Prob',      category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-38', sectorId: 'sec-4', name: 'Gaz Dedektörü',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-39', sectorId: 'sec-4', name: 'Gaz Maskesi / SCBA',  category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-40', sectorId: 'sec-4', name: 'Yalıtım Eldiveni',    category: 'PPE',       createdAt: new Date().toISOString() },
  // ─── TARIM ───
  { id: 'eq-41', sectorId: 'sec-5', name: 'Traktör',             category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-42', sectorId: 'sec-5', name: 'Biçerdöver',          category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-43', sectorId: 'sec-5', name: 'Çapa Makinesi',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-44', sectorId: 'sec-5', name: 'Sulama Pompası',      category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-45', sectorId: 'sec-5', name: 'Zirai İlaç Pompası',  category: 'Tool',      createdAt: new Date().toISOString() },
  { id: 'eq-46', sectorId: 'sec-5', name: 'Solunum Maskesi',     category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-47', sectorId: 'sec-5', name: 'Kimyasal Dayanıklı Elbise', category: 'PPE', createdAt: new Date().toISOString() },
  // ─── SAĞLIK ───
  { id: 'eq-48', sectorId: 'sec-6', name: 'Hasta Karyolası',     category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-49', sectorId: 'sec-6', name: 'Sterilizatör',        category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-50', sectorId: 'sec-6', name: 'Tıbbi Atık Kabı',     category: 'Other',     createdAt: new Date().toISOString() },
  { id: 'eq-51', sectorId: 'sec-6', name: 'Tıbbi Eldiven',       category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-52', sectorId: 'sec-6', name: 'Cerrahi Maske',       category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-53', sectorId: 'sec-6', name: 'Yüz Siperliği',       category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-54', sectorId: 'sec-6', name: 'Tulum / Kıyafet',     category: 'PPE',       createdAt: new Date().toISOString() },
  // ─── GIDA ───
  { id: 'eq-55', sectorId: 'sec-7', name: 'Endüstriyel Fırın',   category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-56', sectorId: 'sec-7', name: 'Endüstriyel Karıştırıcı', category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-57', sectorId: 'sec-7', name: 'Paketleme Makinesi',  category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-58', sectorId: 'sec-7', name: 'Soğuk Hava Düzeni',   category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-59', sectorId: 'sec-7', name: 'Kesim Bıçağı / Makinesi', category: 'Tool', createdAt: new Date().toISOString() },
  { id: 'eq-60', sectorId: 'sec-7', name: 'Hijyen Eldiveni',     category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-61', sectorId: 'sec-7', name: 'Bone / Saç Filesi',   category: 'PPE',       createdAt: new Date().toISOString() },
  // ─── MADENCİLİK ───
  { id: 'eq-62', sectorId: 'sec-8', name: 'Delici Makine',        category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-63', sectorId: 'sec-8', name: 'Patlayıcı Seti',       category: 'Tool',      createdAt: new Date().toISOString() },
  { id: 'eq-64', sectorId: 'sec-8', name: 'Maden Vagoneti',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-65', sectorId: 'sec-8', name: 'Havalandırma Fanı',    category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-66', sectorId: 'sec-8', name: 'Gaz Alarmı',           category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-67', sectorId: 'sec-8', name: 'Maden Lambası',        category: 'PPE',       createdAt: new Date().toISOString() },
  { id: 'eq-68', sectorId: 'sec-8', name: 'SCBA Solunum Cihazı',  category: 'PPE',       createdAt: new Date().toISOString() },
  // ─── KİMYA ───
  { id: 'eq-69', sectorId: 'sec-9', name: 'Basınçlı Reaktör',     category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-70', sectorId: 'sec-9', name: 'Kimyasal Pompa',       category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-71', sectorId: 'sec-9', name: 'Gaz Dedektörü',        category: 'Machinery', createdAt: new Date().toISOString() },
  { id: 'eq-72', sectorId: 'sec-9', name: 'Kimyasal Koruma Elbisesi', category: 'PPE',  createdAt: new Date().toISOString() },
  { id: 'eq-73', sectorId: 'sec-9', name: 'Asit Eldiveni',         category: 'PPE',      createdAt: new Date().toISOString() },
];

export const mockLocationDefinitions: LocationDefinition[] = [
  // Global Lokasyonlar
  { id: 'loc-1',  name: 'Genel Üretim / Çalışma Alanı', type: 'Site',      riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'loc-2',  name: 'Ana Depo',                       type: 'Warehouse', riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'loc-3',  name: 'Ofis Katı',                      type: 'Office',    riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'loc-4',  name: 'Şantiye / Saha',                 type: 'Site',      riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-5',  name: 'Elektrik / Enerji Odası',        type: 'Other',     riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-6',  name: 'Yemekhane',                      type: 'Other',     riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'loc-7',  name: 'WC / Soyunma Odası',             type: 'Other',     riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'loc-8',  name: 'Otopark / Araç Garajı',          type: 'Other',     riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'loc-9',  name: 'Laboratuvar',                    type: 'Other',     riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-10', name: 'Yükleme / Boşaltma Rampası',     type: 'Warehouse', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-11', name: 'Kazan Dairesi / Tesisat Odası',  type: 'Other',     riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'loc-12', name: 'Kompresör / Tüp Gazı Odası',     type: 'Other',     riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'loc-13', name: 'Çatı / Teras',                   type: 'Site',      riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-14', name: 'Boya / Kaplama Atölyesi',        type: 'Site',      riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-15', name: 'Kimyasal Depolama',              type: 'Warehouse', riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  // Firma 1 - TechInşaat
  { id: 'loc-16', companyId: '1', name: 'A Blok',                    type: 'Site',      riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-17', companyId: '1', name: 'B Blok',                    type: 'Site',      riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-18', companyId: '1', name: 'C Blok',                    type: 'Site',      riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-19', companyId: '1', name: 'Temel / Kazı Alanı',        type: 'Site',      riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'loc-20', companyId: '1', name: 'Vinç Parkı',                type: 'Site',      riskLevel: 'Kritik', createdAt: new Date().toISOString() },
  { id: 'loc-21', companyId: '1', name: 'Şantiye Ofisi',             type: 'Office',    riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'loc-22', companyId: '1', name: 'Malzeme Deposu (İnşaat)',   type: 'Warehouse', riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  // Firma 2 - Mega Lojistik
  { id: 'loc-23', companyId: '2', name: 'Soğuk Hava Deposu',         type: 'Warehouse', riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'loc-24', companyId: '2', name: 'Yükleme Rampası (A Kapı)',  type: 'Warehouse', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-25', companyId: '2', name: 'Yükleme Rampası (B Kapı)',  type: 'Warehouse', riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
  { id: 'loc-26', companyId: '2', name: 'TIR Parkı',                 type: 'Other',     riskLevel: 'Orta',   createdAt: new Date().toISOString() },
  { id: 'loc-27', companyId: '2', name: 'Sevkiyat Ofisi',            type: 'Office',    riskLevel: 'Düşük',  createdAt: new Date().toISOString() },
  { id: 'loc-28', companyId: '2', name: 'Akü Şarj İstasyonu',        type: 'Other',     riskLevel: 'Yüksek', createdAt: new Date().toISOString() },
];

export const mockIncidentReasonDefinitions: IncidentReasonDefinition[] = [
  // ─── İNŞAAT ───
  { id: 'rsn-1',  sectorId: 'sec-1', name: 'İskele çökmesi / devrilmesi',         category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-2',  sectorId: 'sec-1', name: 'Yüksekten düşme',                     category: 'Human',       createdAt: new Date().toISOString() },
  { id: 'rsn-3',  sectorId: 'sec-1', name: 'Malzeme / araç gereç düşmesi',        category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-4',  sectorId: 'sec-1', name: 'Beton dökme / pompa kazası',          category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-5',  sectorId: 'sec-1', name: 'Kazı çökmesi / toprak kayması',       category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-6',  sectorId: 'sec-1', name: 'Elektrik çarpması',                   category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-7',  sectorId: 'sec-1', name: 'Toz / silikoz maruziyeti',            category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-8',  sectorId: 'sec-1', name: 'Vinç / kaldırma kazası',              category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-9',  sectorId: 'sec-1', name: 'Kesici alet yaralanması',             category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-10', sectorId: 'sec-1', name: 'Gürültüye bağlı işitme kaybı',        category: 'Environment', createdAt: new Date().toISOString() },
  // ─── LOJİSTİK ───
  { id: 'rsn-11', sectorId: 'sec-2', name: 'Forklift / raf kamyon çarpışması',    category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-12', sectorId: 'sec-2', name: 'Yük / palet devrilmesi',              category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-13', sectorId: 'sec-2', name: 'Araç trafik kazası',                  category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-14', sectorId: 'sec-2', name: 'Manuel yük kaldırma yaralanması',     category: 'Human',       createdAt: new Date().toISOString() },
  { id: 'rsn-15', sectorId: 'sec-2', name: 'Sürücü yorgunluğu / uyku hali',       category: 'Human',       createdAt: new Date().toISOString() },
  { id: 'rsn-16', sectorId: 'sec-2', name: 'Yükleme rampası düşme kazası',        category: 'Environment', createdAt: new Date().toISOString() },
  // ─── SANAYİ ───
  { id: 'rsn-17', sectorId: 'sec-3', name: 'Makineye el / kol sıkışması',         category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-18', sectorId: 'sec-3', name: 'Kesici / delici alet yaralanması',    category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-19', sectorId: 'sec-3', name: 'Kaynak kıvılcımı / yanık',            category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-20', sectorId: 'sec-3', name: 'Kimyasal maruziyet',                  category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-21', sectorId: 'sec-3', name: 'Gürültüye bağlı işitme kaybı',        category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-22', sectorId: 'sec-3', name: 'Titreşim hasarı',                     category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-23', sectorId: 'sec-3', name: 'Ergonomik / tekrarlı hareket hasarı', category: 'Method',      createdAt: new Date().toISOString() },
  { id: 'rsn-24', sectorId: 'sec-3', name: 'Konveyör / bant kazası',              category: 'Equipment',   createdAt: new Date().toISOString() },
  // ─── ENERJİ ───
  { id: 'rsn-25', sectorId: 'sec-4', name: 'Yüksek voltaj elektrik çarpması',     category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-26', sectorId: 'sec-4', name: 'Patlama / yangın',                    category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-27', sectorId: 'sec-4', name: 'Gaz sızıntısı / zehirlenmesi',        category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-28', sectorId: 'sec-4', name: 'Radyasyon maruziyeti',                category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-29', sectorId: 'sec-4', name: 'Kapalı alan boğulması',               category: 'Environment', createdAt: new Date().toISOString() },
  // ─── TARIM ───
  { id: 'rsn-30', sectorId: 'sec-5', name: 'Traktör / iş makinesi devrilmesi',    category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-31', sectorId: 'sec-5', name: 'Pestisit / gübre zehirlenmesi',       category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-32', sectorId: 'sec-5', name: 'Hayvan saldırısı / ısırma',           category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-33', sectorId: 'sec-5', name: 'Güneş çarpması / ısı yorgunluğu',     category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-34', sectorId: 'sec-5', name: 'Alerjik / bitkisel reaksiyon',        category: 'Environment', createdAt: new Date().toISOString() },
  // ─── SAĞLIK ───
  { id: 'rsn-35', sectorId: 'sec-6', name: 'Kesici alet / enjektör yaralanması',  category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-36', sectorId: 'sec-6', name: 'Biyolojik / viral maruziyet',         category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-37', sectorId: 'sec-6', name: 'Kimyasal maruziyet (dezenfektan vb)', category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-38', sectorId: 'sec-6', name: 'Hasta şiddeti / saldırı',             category: 'Human',       createdAt: new Date().toISOString() },
  { id: 'rsn-39', sectorId: 'sec-6', name: 'Aşırı yüklenme / yorgunluk',          category: 'Human',       createdAt: new Date().toISOString() },
  // ─── GIDA ───
  { id: 'rsn-40', sectorId: 'sec-7', name: 'Kesici alet yaralanması',             category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-41', sectorId: 'sec-7', name: 'Kaygan zemin düşme kazası',           category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-42', sectorId: 'sec-7', name: 'Soğuk yanması / hipotermi',           category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-43', sectorId: 'sec-7', name: 'Yüksek ısı yanığı (fırın vb)',        category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-44', sectorId: 'sec-7', name: 'Mikroorganizma / çapraz kirlilik',    category: 'Environment', createdAt: new Date().toISOString() },
  // ─── MADENCİLİK ───
  { id: 'rsn-45', sectorId: 'sec-8', name: 'Göçük / tavan çökmesi',               category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-46', sectorId: 'sec-8', name: 'Patlama (istem dışı)',                category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-47', sectorId: 'sec-8', name: 'Grizu / toz patlaması',               category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-48', sectorId: 'sec-8', name: 'Su baskını / sel',                    category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-49', sectorId: 'sec-8', name: 'Zehirli gaz zehirlenmesi',            category: 'Environment', createdAt: new Date().toISOString() },
  // ─── KİMYA ───
  { id: 'rsn-50', sectorId: 'sec-9', name: 'Kimyasal dökülme / sıçrama',          category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-51', sectorId: 'sec-9', name: 'Reaktör basınç patlaması',            category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-52', sectorId: 'sec-9', name: 'Toksik gaz solunumu',                 category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-53', sectorId: 'sec-9', name: 'Kimyasal yangın',                     category: 'Equipment',   createdAt: new Date().toISOString() },
  // ─── GLOBAL ───
  { id: 'rsn-54', name: 'Kaygan / ıslak zemin',              category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-55', name: 'Dikkatsizlik / hata',               category: 'Human',       createdAt: new Date().toISOString() },
  { id: 'rsn-56', name: 'Yorgunluk / uykusuzluk',            category: 'Human',       createdAt: new Date().toISOString() },
  { id: 'rsn-57', name: 'Yetersiz aydınlatma',               category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-58', name: 'KKD kullanmama / yanlış kullanım',  category: 'Human',       createdAt: new Date().toISOString() },
  { id: 'rsn-59', name: 'Ekipman arızası / eskimesi',        category: 'Equipment',   createdAt: new Date().toISOString() },
  { id: 'rsn-60', name: 'Prosedür / talimat uyumsuzluğu',    category: 'Method',      createdAt: new Date().toISOString() },
  { id: 'rsn-61', name: 'Eğitim yetersizliği',               category: 'Human',       createdAt: new Date().toISOString() },
  { id: 'rsn-62', name: 'Kötü hava / olumsuz çevre koşulları', category: 'Environment', createdAt: new Date().toISOString() },
  { id: 'rsn-63', name: 'Bakım / onarım eksikliği',          category: 'Method',      createdAt: new Date().toISOString() },
  { id: 'rsn-64', name: 'İletişim hatası / yanlış anlama',   category: 'Method',      createdAt: new Date().toISOString() },
  { id: 'rsn-65', name: 'Ergonomik sorun',                   category: 'Method',      createdAt: new Date().toISOString() },
  { id: 'rsn-66', name: 'Panik / stres kaynaklı hata',       category: 'Human',       createdAt: new Date().toISOString() },
];
